{
  "comments": [
    {
      "key": {
        "uuid": "c39df4b9_3248384f",
        "filename": "recipes/recipe_modules/bot_update/resources/bot_update.py",
        "patchSetId": 2
      },
      "lineNbr": 678,
      "author": {
        "id": 1141499
      },
      "writtenOn": "2018-05-09T17:50:16Z",
      "side": 1,
      "message": "hm, are you sure this won\u0027t break bots?\nYour led task failed in bot_update step https://ci.chromium.org/swarming/task/3d5d04c95a1e4f10?server\u003dchromium-swarm.appspot.com with cryptic (to me) error.",
      "range": {
        "startLine": 675,
        "startChar": 0,
        "endLine": 678,
        "endChar": 31
      },
      "revId": "ad5882aead71d910261bb36ecd88eb7f82f7b209",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "6f461af5_454d3d72",
        "filename": "recipes/recipe_modules/bot_update/resources/bot_update.py",
        "patchSetId": 2
      },
      "lineNbr": 679,
      "author": {
        "id": 1141499
      },
      "writtenOn": "2018-05-09T17:50:16Z",
      "side": 1,
      "message": "nit: del 1 empty line",
      "revId": "ad5882aead71d910261bb36ecd88eb7f82f7b209",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}