{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "c1b197fc_ec83cf81",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1339017
      },
      "writtenOn": "2022-11-16T06:21:45Z",
      "side": 1,
      "message": "ptal",
      "revId": "c068ab145029f71d3465cc78c965dc2f1db6babb",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "7681b74d_4c94997e",
        "filename": "presubmit_canned_checks_test.py",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1339017
      },
      "writtenOn": "2022-11-16T06:21:45Z",
      "side": 1,
      "message": "Some of these tests are failing even before my CL. Does CQ/CI run them?",
      "revId": "c068ab145029f71d3465cc78c965dc2f1db6babb",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "5fbf28d3_012e9ba2",
        "filename": "presubmit_canned_checks_test_mocks.py",
        "patchSetId": 1
      },
      "lineNbr": 82,
      "author": {
        "id": 1339017
      },
      "writtenOn": "2022-11-16T06:21:45Z",
      "side": 1,
      "message": "\u003dFalse diverges from the production code and caused some tests to fail",
      "revId": "c068ab145029f71d3465cc78c965dc2f1db6babb",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}