{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "eb0c1be1_fe8e0d93",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1116027
      },
      "writtenOn": "2023-11-14T14:14:45Z",
      "side": 1,
      "message": "Please take a look.",
      "revId": "d0c078165df18d8585449523ce77ce1fe378438f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "c26136ae_6bc835c3",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1116027
      },
      "writtenOn": "2023-11-16T13:18:11Z",
      "side": 1,
      "message": "Anyone knows what this fails?",
      "revId": "d0c078165df18d8585449523ce77ce1fe378438f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "4b95c919_9b728dac",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1116027
      },
      "writtenOn": "2023-11-17T12:21:34Z",
      "side": 1,
      "message": "Can someone help with the CQ failure? They appear to be unrelated to my changes:\n\n    test_ninja_reclient_bins_not_found (__main__.NinjaReclientTest) ... Build is configured to use reclient but necessary binaries or config files can\u0027t be found.\n    Please check if `\"download_remoteexec_cfg\": True` custom var is set in `.gclient`, and run `gclient sync`.\n    ok",
      "revId": "d0c078165df18d8585449523ce77ce1fe378438f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "3ab821e1_3e4d050f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1444553
      },
      "writtenOn": "2023-11-17T15:45:27Z",
      "side": 1,
      "message": "Up, I\u0027ll have a look and see what\u0027s going on here.",
      "parentUuid": "4b95c919_9b728dac",
      "revId": "d0c078165df18d8585449523ce77ce1fe378438f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "bbc672a7_70014772",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1444553
      },
      "writtenOn": "2023-11-17T18:39:13Z",
      "side": 1,
      "message": "I\u0027ve got https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/5038467, which is based on this CL but has an update to the unit test which should address the problem.  Waiting on a dry run to finish before putting up for review.",
      "parentUuid": "3ab821e1_3e4d050f",
      "revId": "d0c078165df18d8585449523ce77ce1fe378438f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "37385e72_d992afdc",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1560543
      },
      "writtenOn": "2023-11-17T19:05:57Z",
      "side": 1,
      "message": "drive-by review. The output is a bit confusing, but actual failure is:\n\n```\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nFAIL: test_ninja_reclient_clears_log_dir (__main__.NinjaReclientTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/b/s/w/ir/cache/vpython/store/cpython-n8umfpv0s1ufm2q1s4irhb59jc/contents/lib/python3.8/unittest/mock.py\", line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File \"depot_tools/tests/ninja_reclient_test.py\", line 328, in test_ninja_reclient_clears_log_dir\n    self.assertCountEqual(os.listdir(log_dir), want_remaining_dirs)\nAssertionError: Element counts were not equal:\nFirst has 1, Second has 0:  \u002720170316T200041.000000_SOME_RANDOM_ID_1\u0027\nFirst has 1, Second has 0:  \u002720170316T200040.000000_SOME_RANDOM_ID_0\u0027\n```\n\nIt\u0027s relevant to your change in reclient_helper.py",
      "parentUuid": "bbc672a7_70014772",
      "revId": "d0c078165df18d8585449523ce77ce1fe378438f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "d67b20ae_b75a5e8d",
        "filename": "reclient_helper.py",
        "patchSetId": 1
      },
      "lineNbr": 274,
      "author": {
        "id": 1116027
      },
      "writtenOn": "2023-11-14T14:15:23Z",
      "side": 1,
      "message": "This is to get a better error message (i.e. see the message from OSError).",
      "revId": "d0c078165df18d8585449523ce77ce1fe378438f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "aaac40be_672afc59",
        "filename": "reclient_helper.py",
        "patchSetId": 1
      },
      "lineNbr": 274,
      "author": {
        "id": 1444553
      },
      "writtenOn": "2023-11-14T17:26:24Z",
      "side": 1,
      "message": "Ack, thanks!",
      "parentUuid": "d67b20ae_b75a5e8d",
      "revId": "d0c078165df18d8585449523ce77ce1fe378438f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}